defaults:
  branches: [release-1.5]
  repo-whitelist: [proxy]
  modifier: release-1.5_am


transforms:

# istio/proxy release-1.5 test jobs(s) - presubmit(s)
- env:
    BAZEL_BUILD_RBE_INSTANCE: projects/prow-cicd/instances/default_instance
    ENVOY_REPOSITORY: https://github.com/istio/envoy
    ENVOY_PREFIX: envoy
  labels:
    preset-enable-netrc: "true"
  job-type: [presubmit]


# istio/proxy release-1.5 build jobs(s) - postsubmit(s)
- env:
    BAZEL_BUILD_RBE_INSTANCE: projects/prow-cicd/instances/default_instance
    GCS_BUILD_BUCKET: am-istio-prow
    GCS_ARTIFACTS_BUCKET: artifacts.prow-cicd.appspot.com
    DOCKER_REPOSITORY: prow-cicd/envoy
    ENVOY_REPOSITORY: https://github.com/istio/envoy
    ENVOY_PREFIX: envoy
  labels:
    preset-enable-netrc: "true"
  job-type: [postsubmit]
