defaults:
  branches: [master]
  repo-whitelist: [proxy]
  modifier: master_am


transforms:

# istio/proxy master test jobs(s) - presubmit(s)
- env:
    BAZEL_BUILD_RBE_INSTANCE: projects/prow-cicd/instances/default_instance
    ENVOY_REPOSITORY: https://github.com/envoyproxy/envoy-wasm
    ENVOY_PREFIX: envoy-wasm
  labels:
    preset-enable-netrc: "true"
  job-type: [presubmit]

# istio/proxy master build jobs(s) - postsubmit(s)
- env:
    BAZEL_BUILD_RBE_INSTANCE: projects/prow-cicd/instances/default_instance
    GCS_BUILD_BUCKET: am-istio-prow
    GCS_ARTIFACTS_BUCKET: artifacts.prow-cicd.appspot.com
    DOCKER_REPOSITORY: prow-cicd/envoy
    ENVOY_REPOSITORY: https://github.com/envoyproxy/envoy-wasm
    ENVOY_PREFIX: envoy-wasm
  labels:
    preset-enable-netrc: "true"
  job-type: [postsubmit]
