---
plank:
  job_url_template: 'https://prow-prod.dev.twistio.io/view/gcs/am-istio-prow{{if eq .Spec.Type "presubmit"}}/pr-logs/pull/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/pr-logs/pull/batch{{else}}/logs{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}'
  job_url_prefix_config:
    '*': https://prow-prod.dev.twistio.io/view/gcs/
  pod_pending_timeout: 15m
  pod_unscheduled_timeout: 5m
  default_decoration_configs:
    '*':
      timeout: 2h
      grace_period: 15s
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20200518-8da074ad4"
        initupload: "gcr.io/k8s-prow/initupload:v20200518-8da074ad4"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20200518-8da074ad4"
        sidecar: "gcr.io/k8s-prow/sidecar:v20200518-8da074ad4"
      gcs_configuration:
        bucket: "am-istio"
        path_strategy: "explicit"
      gcs_credentials_secret: gcs-credentials
      ssh_key_secrets:
        - ssh-key-secret

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 48h
  terminated_pod_ttl: 30m

deck:
  spyglass:
    size_limit: 500000000 # 500MB
    lenses:
    - lens:
        name: metadata
      required_files:
      - started.json|finished.json
      optional_files:
      - podinfo.json
    - lens:
        name: buildlog
      required_files:
      - build-log.txt
    - lens:
        name: junit
      required_files:
      - artifacts/junit.*\.xml
    - lens:
        name: coverage
      required_files:
      - artifacts/filtered.cov
    - lens:
        name: podinfo
      required_files:
      - podinfo.json
    announcement: "This page -- spyglass -- is the default viewer for prow.{{if .ArtifactPath}} For now, the deprecated gubernator page spyglass replaces <a href='https://gubernator.k8s.io/build/{{.ArtifactPath}}'>remains available</a>.{{end}}"
  #hidden_repos:
  #- istio-private

  tide_update_period: 10s
  rerun_auth_configs:
    'aspenmesh':
      github_orgs:
      - aspenmesh
  

prowjob_namespace: default
pod_namespace: test-pods
log_level: debug

slack_reporter_configs:
  '*':
    job_types_to_report:
    - postsubmit
    - periodic
    - batch
    job_states_to_report:
    - failure
    - error
    channel: prow-test-failures
    report_template: 'Job *{{.Spec.Job}}* of type *{{.Spec.Type}}* ended with state *{{.Status.State}}*. <{{.Status.URL}}|View logs>'
 
# Report job status for presubmit and postsubmit
github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit

in_repo_config:
  enabled:
    aspenmesh/istio-private: true
    aspenmesh/cni-private: true
    aspenmesh/proxy-private: true
    aspenmesh/test-infra-private: true
    aspenmesh/release-builder-private: true

# Tide is not enabled fror aspen mesh private repos
tide:
  queries:
  - repos:
    - aspenmesh/istio-private
    - aspenmesh/proxy-private
    - aspenmesh/test-infra-private
    - aspenmesh/cni-private
    - aspenmesh/release-builder-private
    missingLabels:
      - do-not-merge
      - do-not-merge/hold
      - do-not-merge/work-in-progress
      - needs-ok-to-test
      - needs-rebase
    labels:
    - "cla: yes"
    missingLabels: &istio_tide_missing_labels
    author: am-istio-testing
    reviewApprovedRequired: true
  - orgs:
    - some-org-place-holder
    missingLabels: &istio_tide_missing_labels
    reviewApprovedRequired: true
  merge_method:
    aspenmesh/istio-private: squash
    aspenmesh/cni-private: squash
    aspenmesh/proxy-private: squash
    aspenmesh/test-infra-private: squash
    aspenmesh/release-builder-private: squash
  target_url: https://prow-prod.dev.twistio.io/tide
  context_options:
    from-branch-protection: true
    skip-unknown-contexts: true
