# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - aspenmesh/istio-privaate
  - aspenmesh/cni-private
  - aspenmesh/proxy-private
  - aspenmesh/test-infra-private
  - aspenmesh/release-builder-private

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    prow/cluster/jobs/aspenmesh/**/*.yaml:
      name: job-config

slack:
  mergewarnings:
  - repos:
    - aspenmesh/test-infra-private
    channels:
    - am-prow
    whitelist:
    - istio-testing

lgtm:
- repos:
  - aspenmesh/istio-private
  - aspenmesh/cni-private
  - aspenmesh/proxy-private
  - aspenmesh/release-builder-private
  review_acts_as_lgtm: true
  trusted_team_for_sticky_lgtm: "Istio Hackers"

plugins:
  aspenmesh/istio-private:
  - size
  - trigger
  - wip

  aspenmesh/cni-private:
  - size
  - trigger
  - wip 

  aspenmesh/proxy-private:
  - size
  - trigger
  - wip   

  aspenmesh/test-infra-private:
  - size
  - assign
  - config-updater
  - golint
  - hold
  - lifecycle
  - skip
  - slackevents

  aspenmesh/release-builder-private:
  - size
  - trigger
  - wip
  
external_plugins:
  aspenmesh/istio-private:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
      - issue_comment
      - pull_request
      
  aspenmesh/cni-private:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
    - issue_comment
    - pull_request 

  aspenmesh/proxy-private:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
    - issue_comment
    - pull_request 